### ISSUE TITLE
PyPDF in Windows_10

### ISSUE THREAD

**Issue by yerkobits** [Goro2030/RUTCracker#1]
PyPDF2 is deprecated.

You must install this dependency:

`pip install pypdf`

And then, change [this ](https://github.com/Goro2030/RUTCracker/blob/69a8771618c5370d776e30754fe56d5e2b2b0ec2/abrir_mi_resumen.py#L4
) in code-source:

`from pypdf import PdfReader, PdfWriter`

**Comment by Goro2030** [comment]
You are right. During development I saw that warning and installed the other library. Will fix.

**Comment by Goro2030** [comment]
@yerkobits , I tried to use the new version but it won't support heavier encryption. The one I've used with PyPDF2 should be working eventough is deprecated. 

Have it compiled and worked ok for you with PyPDF2?

**Comment by yerkobits** [comment]
PyPDF2 doesn't work for me.
(Windows 10, Python 3.1)

`pip show pypdf`
Name: pypdf
Version: 3.9.1
Summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
Home-page:
Author:
Author-email: Mathieu Fenniak <biziqe@mathieu.fenniak.net>
License:
Location: c:\python310\lib\site-packages
Requires:
Required-by:


`pip show pypdf2`
Name: PyPDF2
Version: 1.26.0
Summary: PDF toolkit
Home-page: http://mstamy2.github.com/PyPDF2
Author: Mathieu Fenniak
Author-email: biziqe@mathieu.fenniak.net
License:
Location: c:\python310\lib\site-packages
Requires:
Required-by:

> 
> Have it compiled and worked ok for you with PyPDF2?

**Comment by Goro2030** [comment]
I'll put in a comment in the README.MD file about this edge-case :)

Thanks for testing!

**Comment by Goro2030** [comment]
I've migrated to the latest version of pypdf as you suggested. It generated a warning message due to AES encryption with some files, that was annoying, so I suppressed it.
